create extension if not exists pgcrypto;

create table if not exists users(id uuid primary key default gen_random_uuid(),email text unique not null,password_hash text not null,full_name text not null default '',phone text,city text,blood_type text,date_of_birth date,role text not null default 'user',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,token_hash text unique not null,expires_at timestamptz not null,created_at timestamptz not null default now());
create table if not exists services(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,name_id text not null,category text not null,description text not null,status text not null default 'live',sort_order int not null default 0,created_at timestamptz not null default now());
create table if not exists providers(id uuid primary key default gen_random_uuid(),name text not null,type text not null,specialty text,city text not null,address text,about text,rating numeric(2,1) default 0,price_from int,languages text[] default array['Bahasa Indonesia'],service_slugs text[] default '{}',is_demo boolean not null default true,verified boolean not null default false,created_at timestamptz not null default now());
create table if not exists bookings(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,provider_id uuid references providers(id) on delete set null,service_slug text not null,patient_name text not null,contact_phone text,scheduled_at timestamptz not null,notes text,status text not null default 'requested',reference text unique not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists family_members(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,name text not null,relation text not null,date_of_birth date,blood_type text,created_at timestamptz not null default now());
create table if not exists health_records(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,title text not null,record_type text not null,record_date date not null default current_date,notes text,created_at timestamptz not null default now());
create table if not exists blood_requests(id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete set null,patient_initials text not null,blood_type text not null,units_needed int not null default 1,hospital text not null,city text not null,urgency text not null default 'normal',note text,status text not null default 'open',is_demo boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists blood_responses(id uuid primary key default gen_random_uuid(),request_id uuid not null references blood_requests(id) on delete cascade,user_id uuid not null references users(id) on delete cascade,display_name text not null default 'GoHealth member',message text not null,created_at timestamptz not null default now());
create table if not exists notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,title text not null,body text,category text not null default 'general',read boolean not null default false,created_at timestamptz not null default now());
create table if not exists partner_applications(id uuid primary key default gen_random_uuid(),org_name text not null,partner_type text not null,contact_name text not null,email text not null,phone text,city text,message text,status text not null default 'received',created_at timestamptz not null default now());
create table if not exists articles(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,excerpt text not null,body text not null,category text not null,read_minutes int not null default 3,is_demo boolean not null default true,created_at timestamptz not null default now());

create index if not exists idx_bookings_user_created on bookings(user_id,created_at desc);
create index if not exists idx_family_user on family_members(user_id);
create index if not exists idx_records_user_date on health_records(user_id,record_date desc);
create index if not exists idx_blood_city_status on blood_requests(city,status,created_at desc);
create index if not exists idx_notifications_user_read on notifications(user_id,read,created_at desc);
